version: "3.8"

services:
  minecraft:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25566:25565"
    environment:
      TYPE: "AUTO_CURSEFORGE"
      # The Curse Forge Developer Console API key to use type AUTO_CURSEFORGE. Escape $ symbols with an additional $
      CF_API_KEY: "$$2a$$10$$KR2v.RNGM5kf2x1sTlpbw.RMMVpz/recSoWHUujOzwWhQPYnxfPe2"
      CF_PAGE_URL: "https://www.curseforge.com/minecraft/modpacks/create-astral/files/5864143"
      MEMORY: "3G"
      VERSION: "1.16.5"
      EULA: "TRUE"
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - /home/miranya/mc-docker-modded:/data
    restart: on-failure:3